"""Remove email from user model

Revision ID: 7613cfcddbc6
Revises: a43112335fdf
Create Date: 2026-06-18 15:21:22.752730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7613cfcddbc6'
down_revision = 'a43112335fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('email_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_change_requests_token'))
        batch_op.drop_index(batch_op.f('ix_email_change_requests_user_id'))

    op.drop_table('email_change_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')
        batch_op.drop_column('email_confirmed_at')
        batch_op.drop_column('is_email_confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_confirmed', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=False))
        batch_op.add_column(sa.Column('email_confirmed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)

    op.create_table('email_change_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('new_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_change_requests_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_change_requests_token'), ['token'], unique=1)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=1)

    # ### end Alembic commands ###
