"""Remove email confirmation

Revision ID: a43112335fdf
Revises: 
Create Date: 2026-06-18 15:01:50.803127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43112335fdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_confirmation_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_confirmation_tokens_token'))

    op.drop_table('email_confirmation_tokens')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('is_email_confirmed',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('(TRUE)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_email_confirmed',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(TRUE)'))
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               type_=sa.VARCHAR(length=10),
               nullable=True)

    op.create_table('email_confirmation_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_confirmation_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_confirmation_tokens_token'), ['token'], unique=1)

    # ### end Alembic commands ###
